#!/usr/bin/env python3

# note : that you have to run this script every time you change the content of the Fs/ directory,
#         otherwise the changes won't be reflected in the web interface and may cause issues. 
#         You can also run it with the --check option to verify that the generated file is up to date without modifying it.

"""Generate the lwIP HTTP filesystem source used by this project."""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path


BYTES_PER_LINE = 12


@dataclass(frozen=True)
class FsEntry:
    path: Path
    url: str
    content: bytes

    @property
    def name_size(self) -> int:
        return len(self.url.encode("utf-8")) + 1


def find_entries(source_dir: Path) -> list[FsEntry]:
    if not source_dir.is_dir():
        raise ValueError(f"source directory does not exist: {source_dir}")

    entries = []
    for path in source_dir.rglob("*"):
        if not path.is_file() or any(part.startswith(".") for part in path.relative_to(source_dir).parts):
            continue
        relative = path.relative_to(source_dir).as_posix()
        entries.append(FsEntry(path, f"/{relative}", path.read_bytes()))

    entries.sort(key=lambda entry: (entry.url.casefold(), entry.url))
    return entries


def format_byte_array(data: bytes) -> str:
    lines = []
    for offset in range(0, len(data), BYTES_PER_LINE):
        chunk = data[offset : offset + BYTES_PER_LINE]
        lines.append("  " + ", ".join(f"0x{value:02x}" for value in chunk) + ",")
    return "\n".join(lines)


def generate_source(entries: list[FsEntry], source_dir: Path) -> str:
    lines = [
        "/*",
        " * Generated by generate_fsdata.py.",
        f" * Source directory: {source_dir.name}/",
        " * Do not edit this file directly.",
        " */",
        "",
        '#include "lwip/apps/fs.h"',
        '#include "lwip/def.h"',
        "",
        "#define NULL 0",
        "",
    ]

    for index, entry in enumerate(entries):
        payload = entry.url.encode("utf-8") + b"\0" + entry.content
        lines.extend(
            [
                f"/* {entry.url.encode('ascii', errors='backslashreplace').decode('ascii')} */",
                f"static const unsigned char data_{index}[] = {{",
                format_byte_array(payload),
                "};",
                "",
            ]
        )

    for index in range(len(entries) - 1, -1, -1):
        next_file = f"&file_{index + 1}" if index + 1 < len(entries) else "NULL"
        entry = entries[index]
        lines.extend(
            [
                f"static const struct fsdata_file file_{index} = {{",
                f"  {next_file},",
                f"  data_{index},",
                f"  data_{index} + {entry.name_size},",
                f"  {len(entry.content)},",
                "  0",
                "};",
                "",
            ]
        )

    root = "&file_0" if entries else "NULL"
    lines.extend([f"#define FS_ROOT {root}", f"#define FS_NUMFILES {len(entries)}", ""])
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    project_dir = Path(__file__).resolve().parent
    parser = argparse.ArgumentParser(
        description="Convert files from Fs/ into LWIP/App/fsdata_custom.c."
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=project_dir / "Fs",
        help="directory containing web files (default: %(default)s)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=project_dir / "LWIP" / "App" / "fsdata_custom.c",
        help="generated C file (default: %(default)s)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the output is up to date without modifying it",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    source_dir = args.source.resolve()
    output_path = args.output.resolve()

    try:
        entries = find_entries(source_dir)
        generated = generate_source(entries, source_dir)
    except (OSError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check:
        try:
            current = output_path.read_text(encoding="ascii")
        except FileNotFoundError:
            current = None
        if current != generated:
            print(f"out of date: {output_path}", file=sys.stderr)
            return 1
        print(f"up to date: {output_path} ({len(entries)} files)")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(generated, encoding="ascii", newline="\n")
    print(f"generated {output_path} from {len(entries)} files")
    for entry in entries:
        print(f"  {entry.url}: {len(entry.content)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
